import type { Config } from 'tailwindcss'
import forms from '@tailwindcss/forms'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#001c8e',
        'tertiary': '#ffa4e4',
        'on-error-container': '#ffb2b9',
        'on-primary-fixed-variant': '#001a88',
        'secondary-container': '#40369f',
        'tertiary-fixed-dim': '#ea82ce',
        'secondary-dim': '#9891fe',
        'on-secondary-fixed': '#2d1f8c',
        'on-secondary-container': '#d0cbff',
        'secondary': '#9891fe',
        'primary-fixed-dim': '#778aff',
        'tertiary-fixed': '#f98fdc',
        'on-error': '#490013',
        'inverse-on-surface': '#565555',
        'on-surface': '#ffffff',
        'surface-container': '#1a1a1a',
        'on-primary-fixed': '#000000',
        'surface-variant': '#262626',
        'on-background': '#ffffff',
        'error-dim': '#d73357',
        'primary-dim': '#4963ff',
        'outline': '#767575',
        'surface': '#0e0e0e',
        'primary': '#9ba8ff',
        'background': '#0e0e0e',
        'on-tertiary-container': '#600653',
        'on-surface-variant': '#adaaaa',
        'tertiary-dim': '#ea82ce',
        'secondary-fixed': '#d1ccff',
        'surface-tint': '#9ba8ff',
        'surface-dim': '#0e0e0e',
        'surface-container-lowest': '#000000',
        'on-tertiary-fixed': '#390030',
        'on-primary-container': '#001470',
        'inverse-surface': '#fcf9f8',
        'secondary-fixed-dim': '#c2bdff',
        'on-secondary': '#170074',
        'outline-variant': '#484847',
        'surface-bright': '#2c2c2c',
        'error-container': '#a70138',
        'primary-container': '#8999ff',
        'surface-container-high': '#20201f',
        'error': '#ff6e84',
        'on-secondary-fixed-variant': '#4a41aa',
        'on-tertiary': '#6d155d',
        'inverse-primary': '#2949ef',
        'surface-container-low': '#131313',
        'surface-container-highest': '#262626',
        'primary-fixed': '#8999ff',
        'on-tertiary-fixed-variant': '#6c135c',
        'tertiary-container': '#f98fdc',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [forms],
}

export default config
